valor = input('Digite um valor: ')
print('Class: {}'.format(type(valor)))
print('É numérico: {}'.format(valor.isnumeric()))
print('É texto: {}'.format(valor.isalpha()))
print('É alfanumérico: {}'.format(valor.isalnum()))
print('É maiúscula: {}'.format(valor.isupper()))
print('A primeira é maiúscula e as demais são minúsculas: {}'.format(valor.istitle()))
print('É decimal: {}'.format(valor.isdecimal()))
print('Só tem espaços? {}'.format(valor.isspace()))
print('')
